// flow-typed signature: 499605b0f6c9037034d6e96c02c14718
// flow-typed version: <<STUB>>/babel-plugin-check-es2015-constants_v^6.22.0/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-check-es2015-constants'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-check-es2015-constants' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-check-es2015-constants/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-check-es2015-constants/lib/index.js' {
  declare module.exports: $Exports<'babel-plugin-check-es2015-constants/lib/index'>;
}
